name: coop_cards_poc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  gradient_widgets: ^0.5.0
  carousel_slider: ^1.3.0
  dots_indicator: ^1.0.0
  rflutter_alert: ^1.0.3
  flutter_credit_card: 0.1.3
  provider: ^3.2.0
  fl_chart: ^0.5.0
  flutter_spinkit: "^4.1.0"
  flutter_form_builder: ^3.6.1 
  flutter_launcher_icons: "^0.7.3"
  pin_code_fields: ^2.3.0+1
  flare_flutter: ^1.8.0
  flutter_staggered_animations: "^0.1.2"
  flutter_native_splash: ^0.1.9
  easy_localization: ^1.3.1
  


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/launcher.png"

flutter_native_splash:
  image: assets/images/splash_icon.png
  color: "15665a"

  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/langs/en-US.json
    - assets/langs/es-US.json


